apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-app
      version: canary
  template:
    metadata:
      labels:
        app: main-app
        version: canary
    spec:
      containers:
      - name: app
        image: nginx:latest